# Generated by Django 3.0.5 on 2020-05-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_system', '0004_studentsmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmarks',
            name='department',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='semester',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
