# Generated by Django 3.0.5 on 2020-05-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_system', '0006_auto_20200501_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmarks',
            name='semester',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], default='1', max_length=10),
        ),
    ]
