# Generated by Django 3.0.5 on 2020-05-02 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks_system', '0012_auto_20200502_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmarks',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_system.Department'),
        ),
    ]
